-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE SEQUENCE IF NOT EXISTS eventplanner_event_id_seq;

CREATE TABLE IF NOT EXISTS public.eventplanner
(
    event_id serial NOT NULL,
    is_owner boolean NOT NULL DEFAULT false,
    date_and_time character varying(20) COLLATE pg_catalog."default" NOT NULL,
    location character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(20) COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default",
    participants integer NOT NULL,
    owner_id integer,
    CONSTRAINT eventplanner_pkey PRIMARY KEY (event_id)
    );

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(50) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT USER,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT unique_username UNIQUE (username)
    );

CREATE TABLE IF NOT EXISTS public.eventplanner_users
(
    eventplanner_participants integer NOT NULL,
    users_user_id serial NOT NULL
);

ALTER TABLE IF EXISTS public.eventplanner
    ADD CONSTRAINT owner_id FOREIGN KEY (owner_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.eventplanner
    ADD CONSTRAINT participants FOREIGN KEY (participants)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fki_participants
    ON public.eventplanner(participants);


ALTER TABLE IF EXISTS public.eventplanner_users
    ADD FOREIGN KEY (eventplanner_participants)
    REFERENCES public.eventplanner (participants) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.eventplanner_users
    ADD FOREIGN KEY (users_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;